=begin
#Kubernetes

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: release-1.35

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

require 'date'
require 'time'

module Kubernetes
  # PodCertificateRequestSpec describes the certificate request.  All fields are immutable after creation.
  class V1beta1PodCertificateRequestSpec
    # maxExpirationSeconds is the maximum lifetime permitted for the certificate.  If omitted, kube-apiserver will set it to 86400(24 hours). kube-apiserver will reject values shorter than 3600 (1 hour).  The maximum allowable value is 7862400 (91 days).  The signer implementation is then free to issue a certificate with any lifetime *shorter* than MaxExpirationSeconds, but no shorter than 3600 seconds (1 hour).  This constraint is enforced by kube-apiserver. `kubernetes.io` signers will never issue certificates with a lifetime longer than 24 hours.
    attr_accessor :max_expiration_seconds

    # nodeName is the name of the node the pod is assigned to.
    attr_accessor :node_name

    # nodeUID is the UID of the node the pod is assigned to.
    attr_accessor :node_uid

    # pkixPublicKey is the PKIX-serialized public key the signer will issue the certificate to.  The key must be one of RSA3072, RSA4096, ECDSAP256, ECDSAP384, ECDSAP521, or ED25519. Note that this list may be expanded in the future.  Signer implementations do not need to support all key types supported by kube-apiserver and kubelet.  If a signer does not support the key type used for a given PodCertificateRequest, it must deny the request by setting a status.conditions entry with a type of \"Denied\" and a reason of \"UnsupportedKeyType\". It may also suggest a key type that it does support in the message field.
    attr_accessor :pkix_public_key

    # podName is the name of the pod into which the certificate will be mounted.
    attr_accessor :pod_name

    # podUID is the UID of the pod into which the certificate will be mounted.
    attr_accessor :pod_uid

    # proofOfPossession proves that the requesting kubelet holds the private key corresponding to pkixPublicKey.  It is contructed by signing the ASCII bytes of the pod's UID using `pkixPublicKey`.  kube-apiserver validates the proof of possession during creation of the PodCertificateRequest.  If the key is an RSA key, then the signature is over the ASCII bytes of the pod UID, using RSASSA-PSS from RFC 8017 (as implemented by the golang function crypto/rsa.SignPSS with nil options).  If the key is an ECDSA key, then the signature is as described by [SEC 1, Version 2.0](https://www.secg.org/sec1-v2.pdf) (as implemented by the golang library function crypto/ecdsa.SignASN1)  If the key is an ED25519 key, the the signature is as described by the [ED25519 Specification](https://ed25519.cr.yp.to/) (as implemented by the golang library crypto/ed25519.Sign).
    attr_accessor :proof_of_possession

    # serviceAccountName is the name of the service account the pod is running as.
    attr_accessor :service_account_name

    # serviceAccountUID is the UID of the service account the pod is running as.
    attr_accessor :service_account_uid

    # signerName indicates the requested signer.  All signer names beginning with `kubernetes.io` are reserved for use by the Kubernetes project.  There is currently one well-known signer documented by the Kubernetes project, `kubernetes.io/kube-apiserver-client-pod`, which will issue client certificates understood by kube-apiserver.  It is currently unimplemented.
    attr_accessor :signer_name

    # unverifiedUserAnnotations allow pod authors to pass additional information to the signer implementation.  Kubernetes does not restrict or validate this metadata in any way.  Entries are subject to the same validation as object metadata annotations, with the addition that all keys must be domain-prefixed. No restrictions are placed on values, except an overall size limitation on the entire field.  Signers should document the keys and values they support.  Signers should deny requests that contain keys they do not recognize.
    attr_accessor :unverified_user_annotations

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'max_expiration_seconds' => :'maxExpirationSeconds',
        :'node_name' => :'nodeName',
        :'node_uid' => :'nodeUID',
        :'pkix_public_key' => :'pkixPublicKey',
        :'pod_name' => :'podName',
        :'pod_uid' => :'podUID',
        :'proof_of_possession' => :'proofOfPossession',
        :'service_account_name' => :'serviceAccountName',
        :'service_account_uid' => :'serviceAccountUID',
        :'signer_name' => :'signerName',
        :'unverified_user_annotations' => :'unverifiedUserAnnotations'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'max_expiration_seconds' => :'Integer',
        :'node_name' => :'String',
        :'node_uid' => :'String',
        :'pkix_public_key' => :'String',
        :'pod_name' => :'String',
        :'pod_uid' => :'String',
        :'proof_of_possession' => :'String',
        :'service_account_name' => :'String',
        :'service_account_uid' => :'String',
        :'signer_name' => :'String',
        :'unverified_user_annotations' => :'Hash<String, String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kubernetes::V1beta1PodCertificateRequestSpec` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kubernetes::V1beta1PodCertificateRequestSpec`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'max_expiration_seconds')
        self.max_expiration_seconds = attributes[:'max_expiration_seconds']
      end

      if attributes.key?(:'node_name')
        self.node_name = attributes[:'node_name']
      end

      if attributes.key?(:'node_uid')
        self.node_uid = attributes[:'node_uid']
      end

      if attributes.key?(:'pkix_public_key')
        self.pkix_public_key = attributes[:'pkix_public_key']
      end

      if attributes.key?(:'pod_name')
        self.pod_name = attributes[:'pod_name']
      end

      if attributes.key?(:'pod_uid')
        self.pod_uid = attributes[:'pod_uid']
      end

      if attributes.key?(:'proof_of_possession')
        self.proof_of_possession = attributes[:'proof_of_possession']
      end

      if attributes.key?(:'service_account_name')
        self.service_account_name = attributes[:'service_account_name']
      end

      if attributes.key?(:'service_account_uid')
        self.service_account_uid = attributes[:'service_account_uid']
      end

      if attributes.key?(:'signer_name')
        self.signer_name = attributes[:'signer_name']
      end

      if attributes.key?(:'unverified_user_annotations')
        if (value = attributes[:'unverified_user_annotations']).is_a?(Hash)
          self.unverified_user_annotations = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @node_name.nil?
        invalid_properties.push('invalid value for "node_name", node_name cannot be nil.')
      end

      if @node_uid.nil?
        invalid_properties.push('invalid value for "node_uid", node_uid cannot be nil.')
      end

      if @pkix_public_key.nil?
        invalid_properties.push('invalid value for "pkix_public_key", pkix_public_key cannot be nil.')
      end

      pattern = Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
      if @pkix_public_key !~ pattern
        invalid_properties.push("invalid value for \"pkix_public_key\", must conform to the pattern #{pattern}.")
      end

      if @pod_name.nil?
        invalid_properties.push('invalid value for "pod_name", pod_name cannot be nil.')
      end

      if @pod_uid.nil?
        invalid_properties.push('invalid value for "pod_uid", pod_uid cannot be nil.')
      end

      if @proof_of_possession.nil?
        invalid_properties.push('invalid value for "proof_of_possession", proof_of_possession cannot be nil.')
      end

      pattern = Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
      if @proof_of_possession !~ pattern
        invalid_properties.push("invalid value for \"proof_of_possession\", must conform to the pattern #{pattern}.")
      end

      if @service_account_name.nil?
        invalid_properties.push('invalid value for "service_account_name", service_account_name cannot be nil.')
      end

      if @service_account_uid.nil?
        invalid_properties.push('invalid value for "service_account_uid", service_account_uid cannot be nil.')
      end

      if @signer_name.nil?
        invalid_properties.push('invalid value for "signer_name", signer_name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @node_name.nil?
      return false if @node_uid.nil?
      return false if @pkix_public_key.nil?
      return false if @pkix_public_key !~ Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
      return false if @pod_name.nil?
      return false if @pod_uid.nil?
      return false if @proof_of_possession.nil?
      return false if @proof_of_possession !~ Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
      return false if @service_account_name.nil?
      return false if @service_account_uid.nil?
      return false if @signer_name.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] pkix_public_key Value to be assigned
    def pkix_public_key=(pkix_public_key)
      if pkix_public_key.nil?
        fail ArgumentError, 'pkix_public_key cannot be nil'
      end

      pattern = Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
      if pkix_public_key !~ pattern
        fail ArgumentError, "invalid value for \"pkix_public_key\", must conform to the pattern #{pattern}."
      end

      @pkix_public_key = pkix_public_key
    end

    # Custom attribute writer method with validation
    # @param [Object] proof_of_possession Value to be assigned
    def proof_of_possession=(proof_of_possession)
      if proof_of_possession.nil?
        fail ArgumentError, 'proof_of_possession cannot be nil'
      end

      pattern = Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
      if proof_of_possession !~ pattern
        fail ArgumentError, "invalid value for \"proof_of_possession\", must conform to the pattern #{pattern}."
      end

      @proof_of_possession = proof_of_possession
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          max_expiration_seconds == o.max_expiration_seconds &&
          node_name == o.node_name &&
          node_uid == o.node_uid &&
          pkix_public_key == o.pkix_public_key &&
          pod_name == o.pod_name &&
          pod_uid == o.pod_uid &&
          proof_of_possession == o.proof_of_possession &&
          service_account_name == o.service_account_name &&
          service_account_uid == o.service_account_uid &&
          signer_name == o.signer_name &&
          unverified_user_annotations == o.unverified_user_annotations
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [max_expiration_seconds, node_name, node_uid, pkix_public_key, pod_name, pod_uid, proof_of_possession, service_account_name, service_account_uid, signer_name, unverified_user_annotations].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Kubernetes.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
