# -*- encoding: utf-8 -*-

=begin
#Kubernetes

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: release-1.35

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "kubernetes/version"

Gem::Specification.new do |s|
  s.name        = "kruby"
  s.version     = Kubernetes::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["doridoridoriand"]
  s.homepage    = "https://github.com/doridoridoriand/kruby"
  s.summary     = "Kruby community client for Kubernetes API."
  s.description = "Kruby is a community-maintained Ruby client generated from Kubernetes OpenAPI."
  s.license     = "Apache-2.0"
  s.required_ruby_version = ">= 3.3.0"
  s.metadata = {
    "homepage_uri" => s.homepage,
    "source_code_uri" => s.homepage,
    "documentation_uri" => "#{s.homepage}#readme",
    "changelog_uri" => "#{s.homepage}/blob/master/CHANGELOG.md",
    "bug_tracker_uri" => "#{s.homepage}/issues",
    "allowed_push_host" => "https://rubygems.org",
    "rubygems_mfa_required" => "true"
  }

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'base64', '~> 0.2'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files = Dir.chdir(__dir__) do
    Dir[
      "LICENSE",
      "README.md",
      "lib/**/*.rb"
    ].select { |f| File.file?(f) }.sort
  end
  s.executables   = []
  s.require_paths = ["lib"]
end
